# Generated by Django 4.2.7 on 2023-11-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('author', models.CharField(db_index=True, max_length=250)),
                ('publication_year', models.IntegerField()),
                ('isbn', models.CharField(db_index=True, max_length=20)),
            ],
        ),
    ]
